@startuml


Player <|-- Movement
Player <|-- Time
Player <|-- Upgrades
Enemy <|-- EnemyMovement
Tiles <|-- Player
Tiles <|-- Enemy

class Player
{
    +void OwnTiles()
    +string CityInfo
}

Class Movement
{
    +void TakeTile()
}

Class EnemyMovement
{
  +Void TimeToTake()
   +Void TakeTile()

}

class Upgrades
{
    +MilitaryPerk: string
    +EconomicPerk: string
    +HappinessPerk: string
    
    +void MIlitaryPerk()
    +Void EconomicPerk()
    +Void HappinessPerk()
}

class Enemy
{
    +void OwnTiles()
}

class Tiles
{
    +Void GrassTile()
}

Class Time
{
    +Void Cash()
    +Void Happiness()
    +Void Military()
}

@enduml