@startuml


Player <-- Movement
Player <-- Time
Player <-- Upgrades
Enemy <-- EnemyMovement
Envoriment <-- Player
Envoriment <-- Enemy
Envoriment <|-- GrassTile
Envoriment <|-- WaterTile
Envoriment <|-- MountainTile
Envoriment <|-- DesertTile
Envoriment <|-- ForestTile
Envoriment <|-- SnowTile
Envoriment <|-- CityTile
Envoriment <|-- TreasureTile

class Envoriment
{
    +Void SpawnMap()
    +Void SpawnPlayer()
    +Void SpawnEnemy()

    +int TileCost
    +string TileInfo
}

class GrassTile
{

}

class WaterTile
{

}

class MountainTile
{

}

class DesertTile
{

}

class ForestTile
{

}

class SnowTile
{

}

class CityTile
{

}

class TreasureTile
{

}
class Player
{
    +void OwnTiles()
    +string CityInfo
}

Class Movement
{
    +void TakeTile()
}

Class EnemyMovement
{
    +Void TimeToTake()
    +Void TakeTile()
}

class Upgrades
{
    +string MilitaryPerk
    +string EconomicPerk
    +string HappinessPerk

    +void MIlitaryPerk()
    +Void EconomicPerk()
    +Void HappinessPerk()
}

class Enemy
{
    +void OwnTiles()
}

Class Time
{
    +Void Cash()
    +Void Happiness()
    +Void Military()
}

@enduml